apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: cert-zimrri
  namespace: gateway
spec:
  dnsNames:
    - "*.zimrri.com"
    - zimrri.com
  issuerRef:
    group: cert-manager.io
    kind: ClusterIssuer
    name: cloudflare-cluster-issuer
  secretName: cert-zimrri
  usages:
    - digital signature
    - key encipherment
